[2024-09-29T00:19:24.470-0500] {processor.py:186} INFO - Started process (PID=28631) to work on /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T00:19:24.471-0500] {processor.py:914} INFO - Processing file /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-29T00:19:24.473-0500] {logging_mixin.py:190} INFO - [2024-09-29T00:19:24.472-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T00:19:24.502-0500] {logging_mixin.py:190} INFO - [2024-09-29T00:19:24.501-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-29T00:19:24.503-0500] {logging_mixin.py:190} INFO - [2024-09-29T00:19:24.503-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-29T00:19:24.503-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T00:19:24.518-0500] {processor.py:208} INFO - Processing /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.056 seconds
[2024-09-29T00:20:48.580-0500] {processor.py:186} INFO - Started process (PID=28706) to work on /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T00:20:48.604-0500] {processor.py:914} INFO - Processing file /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-29T00:20:48.611-0500] {logging_mixin.py:190} INFO - [2024-09-29T00:20:48.610-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T00:20:48.618-0500] {logging_mixin.py:190} INFO - [2024-09-29T00:20:48.617-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-29T00:20:48.618-0500] {logging_mixin.py:190} INFO - [2024-09-29T00:20:48.618-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-29T00:20:48.619-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T00:20:48.632-0500] {processor.py:208} INFO - Processing /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.059 seconds
[2024-09-29T00:22:30.911-0500] {processor.py:186} INFO - Started process (PID=28780) to work on /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T00:22:30.925-0500] {processor.py:914} INFO - Processing file /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-29T00:22:30.928-0500] {logging_mixin.py:190} INFO - [2024-09-29T00:22:30.928-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T00:22:30.933-0500] {logging_mixin.py:190} INFO - [2024-09-29T00:22:30.932-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-29T00:22:30.934-0500] {logging_mixin.py:190} INFO - [2024-09-29T00:22:30.933-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-29T00:22:30.934-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T00:22:30.947-0500] {processor.py:208} INFO - Processing /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-09-29T00:23:57.689-0500] {processor.py:186} INFO - Started process (PID=28852) to work on /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T00:23:57.733-0500] {processor.py:914} INFO - Processing file /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-29T00:23:57.736-0500] {logging_mixin.py:190} INFO - [2024-09-29T00:23:57.735-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T00:23:57.741-0500] {logging_mixin.py:190} INFO - [2024-09-29T00:23:57.740-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-29T00:23:57.741-0500] {logging_mixin.py:190} INFO - [2024-09-29T00:23:57.741-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-29T00:23:57.742-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T00:23:57.758-0500] {processor.py:208} INFO - Processing /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.079 seconds
[2024-09-29T00:25:20.485-0500] {processor.py:186} INFO - Started process (PID=28924) to work on /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T00:25:20.487-0500] {processor.py:914} INFO - Processing file /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-29T00:25:20.492-0500] {logging_mixin.py:190} INFO - [2024-09-29T00:25:20.491-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T00:25:20.497-0500] {logging_mixin.py:190} INFO - [2024-09-29T00:25:20.496-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-29T00:25:20.497-0500] {logging_mixin.py:190} INFO - [2024-09-29T00:25:20.497-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-29T00:25:20.497-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T00:25:20.511-0500] {processor.py:208} INFO - Processing /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2024-09-29T00:26:58.757-0500] {processor.py:186} INFO - Started process (PID=29039) to work on /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T00:26:58.771-0500] {processor.py:914} INFO - Processing file /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-29T00:26:58.775-0500] {logging_mixin.py:190} INFO - [2024-09-29T00:26:58.774-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T00:26:58.780-0500] {logging_mixin.py:190} INFO - [2024-09-29T00:26:58.779-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-29T00:26:58.780-0500] {logging_mixin.py:190} INFO - [2024-09-29T00:26:58.780-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-29T00:26:58.780-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T00:26:58.794-0500] {processor.py:208} INFO - Processing /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2024-09-29T00:28:39.941-0500] {processor.py:186} INFO - Started process (PID=29163) to work on /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T00:28:39.967-0500] {processor.py:914} INFO - Processing file /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-29T00:28:39.970-0500] {logging_mixin.py:190} INFO - [2024-09-29T00:28:39.970-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T00:28:39.975-0500] {logging_mixin.py:190} INFO - [2024-09-29T00:28:39.974-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-29T00:28:39.975-0500] {logging_mixin.py:190} INFO - [2024-09-29T00:28:39.975-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-29T00:28:39.976-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T00:28:39.990-0500] {processor.py:208} INFO - Processing /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.060 seconds
[2024-09-29T00:31:10.151-0500] {processor.py:186} INFO - Started process (PID=29301) to work on /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T00:31:10.222-0500] {processor.py:914} INFO - Processing file /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-29T00:31:10.227-0500] {logging_mixin.py:190} INFO - [2024-09-29T00:31:10.227-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T00:31:10.267-0500] {logging_mixin.py:190} INFO - [2024-09-29T00:31:10.266-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-29T00:31:10.268-0500] {logging_mixin.py:190} INFO - [2024-09-29T00:31:10.267-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-29T00:31:10.268-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T00:31:10.288-0500] {processor.py:208} INFO - Processing /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.146 seconds
[2024-09-29T00:32:40.309-0500] {processor.py:186} INFO - Started process (PID=29376) to work on /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T00:32:40.343-0500] {processor.py:914} INFO - Processing file /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-29T00:32:40.350-0500] {logging_mixin.py:190} INFO - [2024-09-29T00:32:40.349-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T00:32:40.354-0500] {logging_mixin.py:190} INFO - [2024-09-29T00:32:40.353-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-29T00:32:40.355-0500] {logging_mixin.py:190} INFO - [2024-09-29T00:32:40.354-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-29T00:32:40.355-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T00:32:40.368-0500] {processor.py:208} INFO - Processing /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.066 seconds
[2024-09-29T00:34:09.606-0500] {processor.py:186} INFO - Started process (PID=29485) to work on /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T00:34:09.647-0500] {processor.py:914} INFO - Processing file /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-29T00:34:09.650-0500] {logging_mixin.py:190} INFO - [2024-09-29T00:34:09.650-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T00:34:09.718-0500] {logging_mixin.py:190} INFO - [2024-09-29T00:34:09.716-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-29T00:34:09.720-0500] {logging_mixin.py:190} INFO - [2024-09-29T00:34:09.719-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-29T00:34:09.720-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T00:34:09.735-0500] {processor.py:208} INFO - Processing /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.137 seconds
[2024-09-29T08:20:38.610-0500] {processor.py:186} INFO - Started process (PID=29783) to work on /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:20:38.634-0500] {processor.py:914} INFO - Processing file /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-29T08:20:38.637-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:20:38.636-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:20:38.655-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:20:38.654-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-29T08:20:38.655-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:20:38.655-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-29T08:20:38.656-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:20:38.671-0500] {processor.py:208} INFO - Processing /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.072 seconds
[2024-09-29T08:22:43.127-0500] {processor.py:186} INFO - Started process (PID=29891) to work on /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:22:43.179-0500] {processor.py:914} INFO - Processing file /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-29T08:22:43.185-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:22:43.184-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:22:43.235-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:22:43.232-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-29T08:22:43.235-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:22:43.235-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-29T08:22:43.236-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:22:43.252-0500] {processor.py:208} INFO - Processing /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.136 seconds
[2024-09-29T08:24:14.081-0500] {processor.py:186} INFO - Started process (PID=29966) to work on /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:24:14.097-0500] {processor.py:914} INFO - Processing file /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-29T08:24:14.100-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:24:14.099-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:24:14.105-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:24:14.104-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-29T08:24:14.106-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:24:14.105-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-29T08:24:14.106-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:24:14.119-0500] {processor.py:208} INFO - Processing /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2024-09-29T08:25:37.918-0500] {processor.py:186} INFO - Started process (PID=30070) to work on /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:25:37.961-0500] {processor.py:914} INFO - Processing file /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-29T08:25:37.967-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:25:37.966-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:25:37.972-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:25:37.971-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-29T08:25:37.972-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:25:37.972-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-29T08:25:37.972-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:25:37.984-0500] {processor.py:208} INFO - Processing /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.074 seconds
[2024-09-29T08:27:03.955-0500] {processor.py:186} INFO - Started process (PID=30139) to work on /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:27:03.980-0500] {processor.py:914} INFO - Processing file /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-29T08:27:03.987-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:27:03.986-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:27:03.994-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:27:03.993-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-29T08:27:03.994-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:27:03.994-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-29T08:27:03.995-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:27:04.007-0500] {processor.py:208} INFO - Processing /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.060 seconds
[2024-09-29T08:28:18.340-0500] {processor.py:186} INFO - Started process (PID=30205) to work on /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:28:18.342-0500] {processor.py:914} INFO - Processing file /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-29T08:28:18.344-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:28:18.344-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:28:18.348-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:28:18.347-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-29T08:28:18.348-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:28:18.348-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-29T08:28:18.349-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:28:18.362-0500] {processor.py:208} INFO - Processing /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2024-09-29T08:29:38.368-0500] {processor.py:186} INFO - Started process (PID=30275) to work on /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:29:38.639-0500] {processor.py:914} INFO - Processing file /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-29T08:29:38.645-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:29:38.644-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:29:38.649-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:29:38.648-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-29T08:29:38.650-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:29:38.650-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-29T08:29:38.650-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:29:38.663-0500] {processor.py:208} INFO - Processing /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.302 seconds
[2024-09-29T08:31:09.717-0500] {processor.py:186} INFO - Started process (PID=30354) to work on /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:31:09.719-0500] {processor.py:914} INFO - Processing file /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-29T08:31:09.721-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:31:09.721-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:31:09.725-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:31:09.724-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-29T08:31:09.725-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:31:09.725-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-29T08:31:09.726-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:31:09.738-0500] {processor.py:208} INFO - Processing /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2024-09-29T08:32:48.059-0500] {processor.py:186} INFO - Started process (PID=30439) to work on /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:32:48.061-0500] {processor.py:914} INFO - Processing file /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-29T08:32:48.063-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:32:48.063-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:32:48.067-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:32:48.066-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-29T08:32:48.067-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:32:48.067-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-29T08:32:48.068-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:32:48.080-0500] {processor.py:208} INFO - Processing /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2024-09-29T08:34:07.354-0500] {processor.py:186} INFO - Started process (PID=30508) to work on /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:34:07.356-0500] {processor.py:914} INFO - Processing file /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-29T08:34:07.358-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:34:07.358-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:34:07.362-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:34:07.361-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-29T08:34:07.362-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:34:07.362-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-29T08:34:07.363-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:34:07.375-0500] {processor.py:208} INFO - Processing /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2024-09-29T08:36:03.756-0500] {processor.py:186} INFO - Started process (PID=30783) to work on /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:36:03.792-0500] {processor.py:914} INFO - Processing file /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-29T08:36:03.796-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:36:03.795-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:36:03.830-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:36:03.827-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-29T08:36:03.831-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:36:03.830-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-29T08:36:03.831-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:36:03.848-0500] {processor.py:208} INFO - Processing /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.099 seconds
[2024-09-29T08:38:12.012-0500] {processor.py:186} INFO - Started process (PID=31057) to work on /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:38:12.040-0500] {processor.py:914} INFO - Processing file /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-29T08:38:12.047-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:38:12.045-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:38:12.073-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:38:12.072-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-29T08:38:12.073-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:38:12.073-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-29T08:38:12.074-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:38:12.088-0500] {processor.py:208} INFO - Processing /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.084 seconds
[2024-09-29T08:39:38.557-0500] {processor.py:186} INFO - Started process (PID=31129) to work on /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:39:38.581-0500] {processor.py:914} INFO - Processing file /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-29T08:39:38.584-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:39:38.584-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:39:38.588-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:39:38.587-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-29T08:39:38.588-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:39:38.588-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-29T08:39:38.588-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:39:38.601-0500] {processor.py:208} INFO - Processing /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.052 seconds
[2024-09-29T08:41:17.531-0500] {processor.py:186} INFO - Started process (PID=31207) to work on /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:41:17.561-0500] {processor.py:914} INFO - Processing file /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-29T08:41:17.566-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:41:17.565-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:41:17.571-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:41:17.570-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-29T08:41:17.572-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:41:17.572-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-29T08:41:17.572-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:41:17.584-0500] {processor.py:208} INFO - Processing /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.061 seconds
[2024-09-29T08:42:46.439-0500] {processor.py:186} INFO - Started process (PID=31279) to work on /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:42:46.441-0500] {processor.py:914} INFO - Processing file /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-29T08:42:46.443-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:42:46.443-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:42:46.447-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:42:46.446-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-29T08:42:46.447-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:42:46.447-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-29T08:42:46.448-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:42:46.460-0500] {processor.py:208} INFO - Processing /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2024-09-29T08:44:13.834-0500] {processor.py:186} INFO - Started process (PID=31350) to work on /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:44:13.867-0500] {processor.py:914} INFO - Processing file /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-29T08:44:13.872-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:44:13.871-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:44:13.880-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:44:13.879-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-29T08:44:13.881-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:44:13.881-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-29T08:44:13.882-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:44:13.898-0500] {processor.py:208} INFO - Processing /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.072 seconds
[2024-09-29T08:45:36.730-0500] {processor.py:186} INFO - Started process (PID=31433) to work on /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:45:36.758-0500] {processor.py:914} INFO - Processing file /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-29T08:45:36.764-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:45:36.763-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:45:36.769-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:45:36.768-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-29T08:45:36.770-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:45:36.769-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-29T08:45:36.771-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:45:36.789-0500] {processor.py:208} INFO - Processing /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.067 seconds
[2024-09-29T08:47:37.839-0500] {processor.py:186} INFO - Started process (PID=31505) to work on /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:47:37.854-0500] {processor.py:914} INFO - Processing file /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-29T08:47:37.858-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:47:37.857-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:47:37.862-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:47:37.861-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-29T08:47:37.863-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:47:37.863-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-29T08:47:37.863-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:47:37.876-0500] {processor.py:208} INFO - Processing /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2024-09-29T08:49:02.281-0500] {processor.py:186} INFO - Started process (PID=31593) to work on /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:49:02.368-0500] {processor.py:914} INFO - Processing file /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-29T08:49:02.375-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:49:02.374-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:49:02.381-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:49:02.380-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-29T08:49:02.381-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:49:02.381-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-29T08:49:02.382-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:49:02.396-0500] {processor.py:208} INFO - Processing /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.123 seconds
[2024-09-29T08:50:31.924-0500] {processor.py:186} INFO - Started process (PID=31684) to work on /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:50:31.958-0500] {processor.py:914} INFO - Processing file /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-29T08:50:31.967-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:50:31.965-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:50:31.974-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:50:31.973-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-29T08:50:31.974-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:50:31.974-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-29T08:50:31.974-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:50:31.987-0500] {processor.py:208} INFO - Processing /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2024-09-29T08:53:10.348-0500] {processor.py:186} INFO - Started process (PID=31978) to work on /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:53:10.369-0500] {processor.py:914} INFO - Processing file /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-29T08:53:10.375-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:53:10.373-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:53:10.402-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:53:10.401-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-29T08:53:10.403-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:53:10.403-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-29T08:53:10.403-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:53:10.420-0500] {processor.py:208} INFO - Processing /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.081 seconds
[2024-09-29T08:54:43.857-0500] {processor.py:186} INFO - Started process (PID=32055) to work on /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:54:43.885-0500] {processor.py:914} INFO - Processing file /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-29T08:54:43.889-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:54:43.888-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:54:43.894-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:54:43.893-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-29T08:54:43.894-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:54:43.894-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-29T08:54:43.895-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:54:43.908-0500] {processor.py:208} INFO - Processing /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2024-09-29T08:56:23.530-0500] {processor.py:186} INFO - Started process (PID=32132) to work on /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:56:23.545-0500] {processor.py:914} INFO - Processing file /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-29T08:56:23.549-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:56:23.548-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:56:23.569-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:56:23.568-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-29T08:56:23.570-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:56:23.570-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-29T08:56:23.570-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:56:23.585-0500] {processor.py:208} INFO - Processing /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.063 seconds
[2024-09-29T08:58:13.282-0500] {processor.py:186} INFO - Started process (PID=32214) to work on /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:58:13.284-0500] {processor.py:914} INFO - Processing file /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-29T08:58:13.286-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:58:13.286-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:58:13.290-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:58:13.290-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-29T08:58:13.291-0500] {logging_mixin.py:190} INFO - [2024-09-29T08:58:13.291-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-29T08:58:13.291-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T08:58:13.305-0500] {processor.py:208} INFO - Processing /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2024-09-29T09:00:08.022-0500] {processor.py:186} INFO - Started process (PID=32467) to work on /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T09:00:08.023-0500] {processor.py:914} INFO - Processing file /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-29T09:00:08.026-0500] {logging_mixin.py:190} INFO - [2024-09-29T09:00:08.025-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T09:00:08.030-0500] {logging_mixin.py:190} INFO - [2024-09-29T09:00:08.029-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-29T09:00:08.030-0500] {logging_mixin.py:190} INFO - [2024-09-29T09:00:08.030-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-29T09:00:08.031-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T09:00:08.043-0500] {processor.py:208} INFO - Processing /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2024-09-29T09:01:55.648-0500] {processor.py:186} INFO - Started process (PID=32595) to work on /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T09:01:55.663-0500] {processor.py:914} INFO - Processing file /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-29T09:01:55.666-0500] {logging_mixin.py:190} INFO - [2024-09-29T09:01:55.665-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T09:01:55.708-0500] {logging_mixin.py:190} INFO - [2024-09-29T09:01:55.706-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-29T09:01:55.709-0500] {logging_mixin.py:190} INFO - [2024-09-29T09:01:55.709-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-29T09:01:55.710-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T09:01:55.726-0500] {processor.py:208} INFO - Processing /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.085 seconds
[2024-09-29T09:03:21.703-0500] {processor.py:186} INFO - Started process (PID=32665) to work on /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T09:03:21.716-0500] {processor.py:914} INFO - Processing file /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-29T09:03:21.720-0500] {logging_mixin.py:190} INFO - [2024-09-29T09:03:21.719-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T09:03:21.724-0500] {logging_mixin.py:190} INFO - [2024-09-29T09:03:21.723-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-29T09:03:21.725-0500] {logging_mixin.py:190} INFO - [2024-09-29T09:03:21.725-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-29T09:03:21.725-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T09:03:21.738-0500] {processor.py:208} INFO - Processing /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2024-09-29T09:05:05.712-0500] {processor.py:186} INFO - Started process (PID=32951) to work on /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T09:05:05.784-0500] {processor.py:914} INFO - Processing file /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-29T09:05:05.792-0500] {logging_mixin.py:190} INFO - [2024-09-29T09:05:05.790-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T09:05:05.957-0500] {logging_mixin.py:190} INFO - [2024-09-29T09:05:05.955-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-29T09:05:05.958-0500] {logging_mixin.py:190} INFO - [2024-09-29T09:05:05.958-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-29T09:05:05.959-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T09:05:05.973-0500] {processor.py:208} INFO - Processing /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.268 seconds
[2024-09-29T09:07:18.901-0500] {processor.py:186} INFO - Started process (PID=33102) to work on /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T09:07:18.911-0500] {processor.py:914} INFO - Processing file /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-29T09:07:18.914-0500] {logging_mixin.py:190} INFO - [2024-09-29T09:07:18.914-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T09:07:18.923-0500] {logging_mixin.py:190} INFO - [2024-09-29T09:07:18.922-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-29T09:07:18.924-0500] {logging_mixin.py:190} INFO - [2024-09-29T09:07:18.924-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-29T09:07:18.924-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T09:07:18.939-0500] {processor.py:208} INFO - Processing /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2024-09-29T09:08:30.475-0500] {processor.py:186} INFO - Started process (PID=33169) to work on /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T09:08:30.487-0500] {processor.py:914} INFO - Processing file /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-29T09:08:30.490-0500] {logging_mixin.py:190} INFO - [2024-09-29T09:08:30.489-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T09:08:30.495-0500] {logging_mixin.py:190} INFO - [2024-09-29T09:08:30.494-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-29T09:08:30.495-0500] {logging_mixin.py:190} INFO - [2024-09-29T09:08:30.495-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-29T09:08:30.496-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-29T09:08:30.509-0500] {processor.py:208} INFO - Processing /home/d-salamanca/airflow-env/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
